/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.newpackage;

import java.awt.Color;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author oladele
 */
public class test4 extends javax.swing.JFrame {
ResultSet rs ;
    Statement stmt;
    PreparedStatement stat;
    java.sql.Connection con ;
    /**
     * Creates new form test4
     */
    public test4() {
        initComponents();
         
          this.setSize(500,350);
  this. setBackground(Color.BLUE);
        this.setVisible(true);
            this.setLayout(null);
            this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        viewtxt = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        Result = new javax.swing.JTextField();
        View = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setBackground(new java.awt.Color(102, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setText("RESULT:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 170, 80, 30);

        jLabel2.setBackground(new java.awt.Color(102, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setText("SEARCH FOR ORDER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 20, 189, 30);

        jLabel4.setBackground(new java.awt.Color(102, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setText("SALES ID:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 80, 90, 30);

        viewtxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(viewtxt);
        viewtxt.setBounds(60, 260, 90, 40);

        ID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        getContentPane().add(ID);
        ID.setBounds(210, 80, 90, 40);

        Result.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(Result);
        Result.setBounds(210, 170, 90, 40);

        View.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        View.setForeground(new java.awt.Color(0, 0, 0));
        View.setText("VIEW");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });
        getContentPane().add(View);
        View.setBounds(180, 260, 100, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/newpackage/go_back.gif"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 20, 80, 30);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("INVOICE");
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 260, 140, 40);

        jButton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("SEARCH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(170, 130, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/newpackage/work2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-90, -20, 1210, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
if (evt.getActionCommand() == "GENERATE INVOICE") {
              SalesOrder sd = new SalesOrder();
        sd.addComponent();
        dispose();
        }
      if (evt.getActionCommand() == "VIEW") {

      // vso.jButton2=g1;
                   String sql = ("Select * from OLADELE.WORK1 ");
        }
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
         //   con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=netbeans;user=mide;password=1234");   
          con = DriverManager.getConnection("jdbc:derby://localhost:1527/Esuola", "oladele", "Dele");

         stat = con.prepareStatement("Select * from OLADELE.WORK1 where ID = ?");
          stat.setString(1, ID.getText());
        
            rs = stat.executeQuery();
          
            if(rs.next ()){
                 
                JOptionPane.showMessageDialog(null,"TICKETID IS VALID");
                System.out.println("e dey work o");
                 //ViewSalesOrder vso  =new ViewSalesOrder();
                  tes7 ts= new tes7();
           //      vso.ViewSalesOrder();
                ts.SALESID.setText( rs.getString("ID"));
               // Date date=new Date();
     //  String DATE= date.toString();
               Calendar timer=Calendar.getInstance();
        timer.getTime();
        
        
      SimpleDateFormat date=new SimpleDateFormat("dd-MM-YYYY");
       
      String TDATE= date.toString();
      
       ts.DS.setText(date.format(timer.getTime()));
                ts.CS.setText(rs.getString("NAME"));
               ts.PN.setText( rs.getString("phone"));
               ts.A.setText( rs.getString("Address"));
              ts.PSOFA.setText(rs.getString("PSOFA"));
                ts.PDINNIG.setText(rs.getString("PDINNIG"));
              ts.PBED.setText(rs.getString("PBED"));
                ts.PITALIAN.setText(rs.getString("PITALIAN"));
                
                     ts.QSOFA.setText(rs.getString("QSOFA"));
                ts.QDINNIG.setText(rs.getString("QDINNIG"));
              ts.QBED.setText(rs.getString("QBED"));
                ts.QITALIAN.setText(rs.getString("QITALIAN"));
                
                ts.DES.setText(rs.getString("Description"));
                ts.TOTAL.setText(rs.getString("TOTAL"));
                
               
            }
            else {
                JOptionPane.showMessageDialog(null,"Incorrect Details");
                Result.setText("");
              
                
               
            }
            }
            
            catch (Exception ex){
//JOptionPane.showMessageDialog(null,"please enter your ID");


}  
     
    }//GEN-LAST:event_ViewActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
                if (evt.getActionCommand() == "SEARCH") {
            String sql = ("Select * from SIGNUPDETAILS  where Username = ? and Password = ?");
        }
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
         //   con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=netbeans;user=mide;password=1234");   
          con = DriverManager.getConnection("jdbc:derby://localhost:1527/Esuola", "oladele", "Dele");

         stat = con.prepareStatement("Select * from OLADELE.WORK1 where ID = ?");
            stat.setString(1, ID.getText());
        
            rs = stat.executeQuery();
            if(rs.next ()){
                JOptionPane.showMessageDialog(null,"TICKETID IS VALID");
                Result.setText(""+ rs.getString(1));
                viewtxt.setText(""+ rs.getString(1));
               
            }
            
            else {
                JOptionPane.showMessageDialog(null,"Incorrect Details");
                Result.setText("");
              
                
               
            }
            }
            
            catch (Exception ex){
JOptionPane.showMessageDialog(null,"please enter your ID");


}
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
         test5 test=new test5();
            dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new test4().setVisible(true);
                test4 te =new test4();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Result;
    private javax.swing.JButton View;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField viewtxt;
    // End of variables declaration//GEN-END:variables
}
