/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.newpackage;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author oladele
 */

    

/**
 *
 * @author oladele
 */
public class test7 extends javax.swing.JFrame {
java.sql.Connection con ;
    ResultSet rs ;
    Statement stmt;
    PreparedStatement stat;
    /**
     * Creates new form test3
     */
    public test7() {
        initComponents();
         this.setVisible(true);
        this.setSize(930,600);
        this.setLocationRelativeTo(null);
    }
  String[] checked = new String[4];
    Iterator ghdf;
    
    String[] price= new String[4];
    String[] quant= new  String[4];
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        QSOFA = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        EMAIL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DINNIG = new javax.swing.JCheckBox();
        BED = new javax.swing.JCheckBox();
        ITALIAN = new javax.swing.JCheckBox();
        SOFA = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        QDINNIG = new javax.swing.JTextField();
        QBED = new javax.swing.JTextField();
        TOTAL = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        QITALIAN = new javax.swing.JTextField();
        Description = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        PSOFA = new javax.swing.JTextField();
        PDINNIG = new javax.swing.JTextField();
        PBED = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        PITALIAN = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("PHONE NUMBER:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 180, 170, 40);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("SALES ORDER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 0, 170, 40);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 255));
        jLabel5.setText("DINNING TABLE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 350, 120, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setText(" ADDRESS :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 180, 170, 40);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("CUSTOMER NAME :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 120, 170, 40);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 255));
        jLabel7.setText("EMAIL ADDRESS :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 120, 170, 40);

        Phone.setBackground(new java.awt.Color(255, 255, 255));
        Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneActionPerformed(evt);
            }
        });
        getContentPane().add(Phone);
        Phone.setBounds(210, 180, 190, 40);

        QSOFA.setEnabled(false);
        QSOFA.setBackground(new java.awt.Color(255, 255, 255));
        QSOFA.setText("1");
        QSOFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QSOFAActionPerformed(evt);
            }
        });
        getContentPane().add(QSOFA);
        QSOFA.setBounds(440, 320, 50, 30);

        Name.setBackground(new java.awt.Color(255, 255, 255));
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        getContentPane().add(Name);
        Name.setBounds(210, 130, 190, 40);

        EMAIL.setBackground(new java.awt.Color(255, 255, 255));
        EMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMAILActionPerformed(evt);
            }
        });
        getContentPane().add(EMAIL);
        EMAIL.setBounds(580, 120, 190, 40);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 255));
        jLabel8.setText("TICKET ID :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 40, 170, 40);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 255));
        jLabel9.setText("KING SIZED BED");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 390, 120, 30);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 255));
        jLabel10.setText("TOTAL :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 490, 110, 30);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 255, 255));
        jLabel11.setText("ITEM");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(120, 270, 70, 30);

        DINNIG.setText("DINNIG");
        DINNIG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DINNIGActionPerformed(evt);
            }
        });
        getContentPane().add(DINNIG);
        DINNIG.setBounds(230, 361, 20, 20);

        BED.setText("BED");
        BED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEDActionPerformed(evt);
            }
        });
        getContentPane().add(BED);
        BED.setBounds(230, 400, 45, 23);

        ITALIAN.setText("ITALIAN");
        ITALIAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITALIANActionPerformed(evt);
            }
        });
        getContentPane().add(ITALIAN);
        ITALIAN.setBounds(230, 440, 64, 23);

        SOFA.setText("SOFA");
        SOFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOFAActionPerformed(evt);
            }
        });
        getContentPane().add(SOFA);
        SOFA.setBounds(230, 320, 54, 23);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 255, 255));
        jLabel12.setText("DESCRIPTION");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(610, 270, 110, 30);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 255, 255));
        jLabel13.setText("SOFA");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(60, 310, 70, 30);

        QDINNIG.setEnabled(false);
        QDINNIG.setBackground(new java.awt.Color(255, 255, 255));
        QDINNIG.setText("1");
        QDINNIG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QDINNIGActionPerformed(evt);
            }
        });
        getContentPane().add(QDINNIG);
        QDINNIG.setBounds(440, 360, 50, 30);

        QBED.setEnabled(false);
        QBED.setBackground(new java.awt.Color(255, 255, 255));
        QBED.setText("1");
        QBED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QBEDActionPerformed(evt);
            }
        });
        getContentPane().add(QBED);
        QBED.setBounds(440, 400, 50, 30);

        TOTAL.setEditable(false);
        TOTAL.setBackground(new java.awt.Color(255, 255, 255));
        TOTAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TOTALMouseClicked(evt);
            }
        });
        TOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTALActionPerformed(evt);
            }
        });
        getContentPane().add(TOTAL);
        TOTAL.setBounds(160, 490, 120, 30);

        ID.setEditable(false);
        Random rd=new Random();
        int n=rd.nextInt(100000)+1;
        String sg=String.valueOf(n);
        ID.setText(sg);
        ID.setBackground(new java.awt.Color(255, 255, 255));
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        getContentPane().add(ID);
        ID.setBounds(300, 50, 50, 30);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 255, 255));
        jLabel14.setText("ITALIAN CHAIR");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 430, 110, 30);

        QITALIAN.setEnabled(false);
        QITALIAN.setBackground(new java.awt.Color(255, 255, 255));
        QITALIAN.setText("1");
        QITALIAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QITALIANActionPerformed(evt);
            }
        });
        getContentPane().add(QITALIAN);
        QITALIAN.setBounds(440, 440, 50, 30);

        Description.setBackground(new java.awt.Color(255, 255, 255));
        Description.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(Description);
        Description.setBounds(580, 320, 190, 70);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 255, 255));
        jLabel15.setText("PRICE");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(310, 270, 70, 30);

        PSOFA.setEditable(false);
        PSOFA.setBackground(new java.awt.Color(255, 255, 255));
        PSOFA.setText("0");
        PSOFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSOFAActionPerformed(evt);
            }
        });
        getContentPane().add(PSOFA);
        PSOFA.setBounds(310, 320, 50, 30);

        PDINNIG.setEditable(false);
        PDINNIG.setBackground(new java.awt.Color(255, 255, 255));
        PDINNIG.setText("0");
        PDINNIG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDINNIGActionPerformed(evt);
            }
        });
        getContentPane().add(PDINNIG);
        PDINNIG.setBounds(310, 360, 50, 30);

        PBED.setEditable(false);
        PBED.setBackground(new java.awt.Color(255, 255, 255));
        PBED.setText("0");
        PBED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PBEDActionPerformed(evt);
            }
        });
        getContentPane().add(PBED);
        PBED.setBounds(310, 400, 50, 30);

        Address.setBackground(new java.awt.Color(255, 255, 255));
        Address.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(Address);
        Address.setBounds(580, 190, 190, 70);

        PITALIAN.setEditable(false);
        PITALIAN.setBackground(new java.awt.Color(255, 255, 255));
        PITALIAN.setText("0");
        PITALIAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PITALIANActionPerformed(evt);
            }
        });
        getContentPane().add(PITALIAN);
        PITALIAN.setBounds(310, 440, 50, 30);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 255, 255));
        jLabel16.setText("QUANTITY");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(440, 270, 70, 30);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 255, 255));
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 510, 120, 40);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/newpackage/go_back.gif"))); // NOI18N
        jLabel17.setText("jLabel17");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17);
        jLabel17.setBounds(40, 10, 80, 40);

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 255, 255));
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(610, 510, 120, 40);

        jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 255, 255));
        jButton4.setText("Log Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(790, 10, 120, 40);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 255, 255));
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 510, 120, 40);

        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/newpackage/work2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-930, -120, 1860, 820);

        pack();
    }// </editor-fold>                        

    private void PhoneActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void QSOFAActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:   
        
    }                                     

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void EMAILActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void DINNIGActionPerformed(java.awt.event.ActionEvent evt) {                                       

  double n1,n3;
 
        String n4;
       
        //checked[3] = "DINNIG";
        //price[3] = PDINNIG.getText();
          //  quant[3]= QDINNIG.getText();
         if (evt.getActionCommand() == "DINNIG") {
           
            if(DINNIG.isSelected())
                  QDINNIG.setEnabled(true);
                 QDINNIG.getText();
                 QDINNIG.requestFocus();
try{
             {
                 
                n3 = 1500;
                double temp =  n3;
               //jTextField11.setText("" + temp);
                 n1 = Double.parseDouble(QDINNIG.getText());
                double gem=n1;
                 PDINNIG.setText("" + gem*n3);
            }
         }
             catch (Exception e) {
            System.out.println("Error : " + e);
             }
         }

        // TODO add your handling code here:
    }                                      

    private void QDINNIGActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void QBEDActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void TOTALActionPerformed(java.awt.event.ActionEvent evt) {                                      
if(DINNIG.isSelected()){
    double n1,n2,n3,n4;
    n1 = Double.parseDouble(PBED.getText());
    n2=Double.parseDouble(PITALIAN.getText());
    n3=Double.parseDouble(PSOFA.getText());
    n4=Double.parseDouble(PDINNIG.getText());
    double temp=n1+n2+n3+n4;
    TOTAL.setText("" + temp);
}
if(SOFA.isSelected()){
    double n1,n2,n3,n4;
    n1 = Double.parseDouble(PBED.getText());
    n2=Double.parseDouble(PITALIAN.getText());
    n3=Double.parseDouble(PSOFA.getText());
    n4=Double.parseDouble(PDINNIG.getText());
    double temp=n1+n2+n3+n4;
    TOTAL.setText("" + temp);
}
if(BED.isSelected()){
    double n1,n2,n3,n4;
    n1 = Double.parseDouble(PBED.getText());
    n2=Double.parseDouble(PITALIAN.getText());
    n3=Double.parseDouble(PSOFA.getText());
    n4=Double.parseDouble(PDINNIG.getText());
    double temp=n1+n2+n3+n4;
    TOTAL.setText("" + temp);
}
if(ITALIAN.isSelected()){
    double n1,n2,n3,n4;
    n1 = Double.parseDouble(PBED.getText());
    n2=Double.parseDouble(PITALIAN.getText());
    n3=Double.parseDouble(PSOFA.getText());
    n4=Double.parseDouble(PDINNIG.getText());
    double temp=n1+n2+n3+n4;
    TOTAL.setText("" + temp);
}
    // TODO add your handling code here:
    }                                     

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void QITALIANActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void PSOFAActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void PDINNIGActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void PBEDActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void PITALIANActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        
  
    private void SOFAActionPerformed(java.awt.event.ActionEvent evt) {                                     
        
       // checked[0] = "SOFA";
        System.out.println("sofa");
        double n1,n3;
        
        String n4;
            
        // price[0] = PSOFA.getText();
        //quant[0]= QSOFA.getText();
         if (evt.getActionCommand() == "SOFA") {
           
            if(SOFA.isSelected())
try{
             {
                  QSOFA.setEnabled(true);
                 QSOFA.getText();
                 QSOFA.requestFocus();
                n3 = 1000;
                
               // jTextField10.setText("" + temp);
               
                 n1 = Double.parseDouble(QSOFA.getText());
                
              
               double gem=n1;
                PSOFA.setText("" + gem*n3);
            }
         }
          catch (Exception e) {
            System.out.println("Error : " + e);
        
          }
         }
    }                                    

    private void BEDActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
       // checked[1] = "BED";
        double n1,n3;
        String n4;
            
       //  price[1] = PBED.getText();
       // quant[1]= QBED.getText();
        if (evt.getActionCommand() == "BED") {
           
            if(BED.isSelected())
try{
             {
                  QBED.setEnabled(true);
                 QBED.getText();
                 QBED.requestFocus();
                 
                n3 = 2200;
                double temp =  n3;
                //jTextField12.setText("" + temp);
                 n1 = Double.parseDouble(QBED.getText());
                double gem=n1;
                 PBED.setText("" + gem*n3);
            }
           
         }
             catch (Exception e) {
            System.out.println("Error : " + e);
        } 
        }   
    }                                   

    private void ITALIANActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
       // checked[2] = "ITALIAN";
        // price[2] = PITALIAN.getText();
        // quant[2]= QITALIAN.getText();
        double n1,n3;
        String n4;
         if (evt.getActionCommand() == "ITALIAN") {
           try{
               
            if(ITALIAN.isSelected())
 QITALIAN.setEnabled(true);
                 QITALIAN.getText();
                 QITALIAN.requestFocus();
             {
                 
                n3 = 3700;
                double temp =  n3;
                n1 = Double.parseDouble(QITALIAN.getText());
                double gem=n1;
              // jTextField13.setText("" + temp);                 
                //int gem=n1;
                 PITALIAN.setText("" + gem*n3);
            }
         } catch (Exception e) {
            System.out.println("Error : " + e);
         }
         }
    }                                       

    private void TOTALMouseClicked(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:if(jCheckBox1.isSelected()){
    double n1,n2,n3,n4;
    n1 =Double.parseDouble(PBED.getText());
    n2=Double.parseDouble(PITALIAN.getText());
    n3=Double.parseDouble(PSOFA.getText());
    n4=Double.parseDouble(PDINNIG.getText());
    double temp=n1+n2+n3+n4;
    TOTAL.setText("$" + temp);
    }                                  

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
if (evt.getActionCommand() == "RESET")
    SOFA.setSelected(false);
    PSOFA.setText("0");
    QSOFA.setText("1");
    QSOFA.setEnabled(false);

      DINNIG.setSelected(false);
    PDINNIG.setText("0");
    QDINNIG.setText("1");
    QDINNIG.setEnabled(false);
    
      BED.setSelected(false);
    PBED.setText("0");
    QBED.setText("1");
    QBED.setEnabled(false);
    
     ITALIAN.setSelected(false);
    PITALIAN.setText("0");
    QITALIAN.setText("1");
    QITALIAN.setEnabled(false);
    
    TOTAL.setText("");
    
    
        // TODO add your handling code here:
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        {
            try {

                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

                con = DriverManager.getConnection("jdbc:derby://localhost:1527/Esuola", "Oladele", "Dele");

                //      con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=NewBank;user=dele;password=1234");
                stmt = con.createStatement();

            } catch (Exception e) {
                System.out.println("Error : " + e);
            }

         if (evt.getActionCommand() == "SAVE") {
            Pattern Mypattern = Pattern.compile("^[a-z]+[a-z.0-9-]+@[a-z]+(\\.[a-z]+[a-z]+)([/?].*)?$");
           Matcher Mymatcher = Mypattern.matcher(EMAIL.getText());
           Boolean Myboolean = Mymatcher.matches();

            Pattern Mypattern1 = Pattern.compile("^[0-9]+[0-9]");
            Matcher Mymatcher1 = Mypattern1.matcher(Phone.getText());
            Boolean Myboolean1 = Mymatcher1.matches();
            if (Myboolean == true) {
                if (Myboolean1 == true) {
                    if (!Name.getText().equals("")) {
                        try {
                            stat = con.prepareStatement("INSERT INTO WORK1 VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                            
                            int id = Integer.parseInt(ID.getText());
                            String pid = Name.getText();
                            String pname = EMAIL.getText();
                            String pphone = Phone.getText();
                            String padd = Address.getText();
                         String pQUAN = PSOFA.getText();
                          String pQUAN1 = PDINNIG.getText();
                          String pQUAN2= PBED.getText();
                          String pQUAN3= PITALIAN.getText();
                          String pItem= QSOFA.getText();
                          String pItem1 = QDINNIG.getText();
                          String pItem2= QBED.getText();
                          String pItem3= QITALIAN.getText();
                            String pzip = Description.getText();
                            String Tt= TOTAL.getText();
                            
                            stat.setInt(1, id);
                            stat.setString(2, pid);
                            stat.setString(3, pname);
                            stat.setString(4, pphone);
                            stat.setString(5, padd);
                            stat.setString(6,pItem);
                            stat.setString(7,  pItem1);
                             
                            stat.setString(8,  pItem2);
                           
                            stat.setString(9, pQUAN);
                            stat.setString(10, pQUAN1);
                            stat.setString(11, pQUAN2);
                             stat.setString(12, pQUAN3);
                             stat.setString(13, pzip);
                              stat.setString(14, Tt);       
                                   stat.setString(15,  pItem3);  
                                     
                                     
                                     
                            stat.executeUpdate();
                           
                         //   t1.setText("");
                         Name.setText("");
                            EMAIL.setText("");
                            Phone.setText("");
                            Address.setText("");
                            SOFA.setText("");
                            QSOFA.setText("");
                             PSOFA.setText("");
                            Description.setText("");
                            
                            
                             SOFA.setSelected(false);
    PSOFA.setText("0");
    QSOFA.setText("1");
    QSOFA.setEnabled(false);

      DINNIG.setSelected(false);
    PDINNIG.setText("0");
    QDINNIG.setText("1");
    QDINNIG.setEnabled(false);
    
      BED.setSelected(false);
    PBED.setText("0");
    QBED.setText("1");
    QBED.setEnabled(false);
    
     ITALIAN.setSelected(false);
    PITALIAN.setText("0");
    QITALIAN.setText("1");
    QITALIAN.setEnabled(false);
    
    TOTAL.setText("");

                            JOptionPane.showMessageDialog(this, "Information has been inserted.", "Information", JOptionPane.INFORMATION_MESSAGE);

                            int n = JOptionPane.showConfirmDialog(this, "Do you want to Make Another Order?", "Information", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                            if (n == JOptionPane.YES_OPTION) {
                              
                                  ID.setText("");
                            Name.setText("");
                            EMAIL.setText("");
                            Phone.setText("");
                            Address.setText("");
                            SOFA.setText("");
                            QSOFA.setText("");
                             PSOFA.setText("");
                            Description.setText("");
                            
                            
                             SOFA.setSelected(false);
    PSOFA.setText("0");
    QSOFA.setText("1");
    QSOFA.setEnabled(false);

      DINNIG.setSelected(false);
    PDINNIG.setText("0");
    QDINNIG.setText("1");
    QDINNIG.setEnabled(false);
    
      BED.setSelected(false);
    PBED.setText("0");
    QBED.setText("1");
    QBED.setEnabled(false);
    
     ITALIAN.setSelected(false);
    PITALIAN.setText("0");
    QITALIAN.setText("1");
    QITALIAN.setEnabled(false);
    
    TOTAL.setText("");
                           
                            } else {
                                 test4 te =new test4();
                          
    
                                this.dispose();

                            }
                        } catch (Exception e) {
System.out.println("error bikoooo");
                          String msg = e.getMessage();

                            {      JOptionPane.showMessageDialog(this, "Record already exists.", "Warning Message", JOptionPane.WARNING_MESSAGE);
                             // ID.setText("");
                                Name.setText("");
                            EMAIL.setText("");
                            Phone.setText("");
                            Address.setText("");
                            SOFA.getText();
                             QSOFA.setText("");
                          PSOFA.setText("");
                            Description.setText("");
                            
                             SOFA.setSelected(false);
    PSOFA.setText("0");
    QSOFA.setText("1");
    QSOFA.setEnabled(false);

      DINNIG.setSelected(false);
    PDINNIG.setText("0");
    QDINNIG.setText("1");
    QDINNIG.setEnabled(false);
    
      BED.setSelected(false);
    PBED.setText("0");
    QBED.setText("1");
    QBED.setEnabled(false);
    
     ITALIAN.setSelected(false);
    PITALIAN.setText("0");
    QITALIAN.setText("1");
    QITALIAN.setEnabled(false);
    
    TOTAL.setText("");
                            
                            

                        
                        
                            }
                        }
                        }
                    
                     else {
                        JOptionPane.showMessageDialog(this, "Please fill the details properly.", "Error Message", JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "incorrect phone number");
                    JOptionPane.showMessageDialog(this, "Please fill the details properly.", "Error Message", JOptionPane.ERROR_MESSAGE);

                }
            } else {
                JOptionPane.showMessageDialog(this, " Email-id is incorrect");
                JOptionPane.showMessageDialog(this, "Please fill the details properly.", "Error Message", JOptionPane.ERROR_MESSAGE);
            }
         
 
        }
                    
                
            
            
    
    
            
         } 
    
    }                                        

    
    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {                                      
test5 test=new test5();
this.dispose();

        
// TODO add your handling code here:
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new test3().setVisible(true);
               test3 tt =new test3();
            }
        });
    }
private String SOFA1;
    // Variables declaration - do not modify                     
    private javax.swing.JTextField Address;
    private javax.swing.JCheckBox BED;
    private javax.swing.JCheckBox DINNIG;
    private javax.swing.JTextField Description;
    private javax.swing.JTextField EMAIL;
    private javax.swing.JTextField ID;
    private javax.swing.JCheckBox ITALIAN;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField PBED;
    private javax.swing.JTextField PDINNIG;
    private javax.swing.JTextField PITALIAN;
    private javax.swing.JTextField PSOFA;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField QBED;
    private javax.swing.JTextField QDINNIG;
    private javax.swing.JTextField QITALIAN;
    private javax.swing.JTextField QSOFA;
    private javax.swing.JCheckBox SOFA;
    private javax.swing.JTextField TOTAL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration                   
}


